# fly.toml file generated for laravel-cujaneway on 2022-11-21T09:06:47Z

app = "laravel-cujaneway"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_URL = "https://laravel-cujaneway.fly.dev"
  APP_DEBUG = "true"
  MAIL_MAILER= "ses"
  MAIL_FROM_ADDRESS = "cu.janeway@gmail.com"
  MAIL_FROM_NAME = "www.cujaneway.co.uk"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  DB_CONNECTION = "mysql"
  DB_HOST = "lhr.cujaneway-mysql.internal"
  DB_DATABASE= "cube_theory"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
    release_command = "php /var/www/html/artisan migrate --force"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
